version: '3'

services:
  app-jwt-ratelimit:
    image: quarkus/app-jwt-ratelimit:latest
    container_name: app-jwt-ratelimit
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/quarkus
      QUARKUS_DATASOURCE_REDIS_URL: redis://redis:6379
    networks:
      - work
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
      - redis

  postgres-db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quarkus
    logging:
      options:
        max-size: 10m
    networks:
      - work

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - work

networks:
 work:
  driver: bridge

volumes:
  postgres-db: